name: flutter_infinite_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.6
  http: ^0.12.0
  equatable: ^1.2.0
  rxdart: ^0.23.1

flutter:
  uses-material-design: true
